# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anon_ui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(831, 685)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setGeometry(QtCore.QRect(0, 0, 651, 691))
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.layout = QtWidgets.QGridLayout()
        self.layout.setObjectName("layout")
        self.btn_anonfile = QtWidgets.QPushButton(self.centralwidget)
        self.btn_anonfile.setEnabled(False)
        self.btn_anonfile.setObjectName("btn_anonfile")
        self.layout.addWidget(self.btn_anonfile, 6, 0, 1, 2)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.layout.addWidget(self.line_4, 5, 0, 1, 2)
        self.ptId_recInfo_fields = QtWidgets.QGridLayout()
        self.ptId_recInfo_fields.setObjectName("ptId_recInfo_fields")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.ptId_recInfo_fields.addWidget(self.line_3, 14, 0, 1, 4)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.ptId_recInfo_fields.addWidget(self.label_6, 0, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setObjectName("label_11")
        self.ptId_recInfo_fields.addWidget(self.label_11, 6, 1, 1, 1)
        self.hospadmincode = QtWidgets.QLineEdit(self.centralwidget)
        self.hospadmincode.setEnabled(False)
        self.hospadmincode.setObjectName("hospadmincode")
        self.ptId_recInfo_fields.addWidget(self.hospadmincode, 10, 2, 1, 1)
        self.cbox_copyoriginal = QtWidgets.QCheckBox(self.centralwidget)
        self.cbox_copyoriginal.setEnabled(False)
        self.cbox_copyoriginal.setObjectName("cbox_copyoriginal")
        self.ptId_recInfo_fields.addWidget(self.cbox_copyoriginal, 1, 3, 1, 1)
        self.oldinputStartDate = QtWidgets.QDateEdit(self.centralwidget)
        self.oldinputStartDate.setEnabled(False)
        self.oldinputStartDate.setObjectName("oldinputStartDate")
        self.ptId_recInfo_fields.addWidget(self.oldinputStartDate, 15, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.ptId_recInfo_fields.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.ptId_recInfo_fields.addWidget(self.label_5, 0, 2, 1, 1)
        self.groupBoxSexEdit = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxSexEdit.setEnabled(False)
        self.groupBoxSexEdit.setTitle("")
        self.groupBoxSexEdit.setObjectName("groupBoxSexEdit")
        self.ptId_recInfo_fields.addWidget(self.groupBoxSexEdit, 4, 3, 1, 1)
        self.techcodeedit = QtWidgets.QLineEdit(self.centralwidget)
        self.techcodeedit.setEnabled(False)
        self.techcodeedit.setObjectName("techcodeedit")
        self.ptId_recInfo_fields.addWidget(self.techcodeedit, 11, 3, 1, 1)
        self.ptnameedit = QtWidgets.QLineEdit(self.centralwidget)
        self.ptnameedit.setEnabled(False)
        self.ptnameedit.setObjectName("ptnameedit")
        self.ptId_recInfo_fields.addWidget(self.ptnameedit, 6, 3, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setObjectName("label_17")
        self.ptId_recInfo_fields.addWidget(self.label_17, 16, 1, 1, 1)
        self.oldinputStartTime = QtWidgets.QTimeEdit(self.centralwidget)
        self.oldinputStartTime.setEnabled(False)
        self.oldinputStartTime.setObjectName("oldinputStartTime")
        self.ptId_recInfo_fields.addWidget(self.oldinputStartTime, 16, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setObjectName("label_12")
        self.ptId_recInfo_fields.addWidget(self.label_12, 7, 1, 1, 1)
        self.groupBoxDateEdit = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxDateEdit.setEnabled(False)
        self.groupBoxDateEdit.setTitle("")
        self.groupBoxDateEdit.setObjectName("groupBoxDateEdit")
        self.ptId_recInfo_fields.addWidget(self.groupBoxDateEdit, 5, 3, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.ptId_recInfo_fields.addWidget(self.line_2, 8, 0, 1, 4)
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setObjectName("label_15")
        self.ptId_recInfo_fields.addWidget(self.label_15, 12, 1, 1, 1)
        self.groupBoxDate = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxDate.setEnabled(False)
        self.groupBoxDate.setTitle("")
        self.groupBoxDate.setObjectName("groupBoxDate")
        self.ptId_recInfo_fields.addWidget(self.groupBoxDate, 5, 2, 1, 1)
        self.inputStartTime = QtWidgets.QTimeEdit(self.centralwidget)
        self.inputStartTime.setEnabled(False)
        self.inputStartTime.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 12, 1), QtCore.QTime(0, 0, 0)))
        self.inputStartTime.setObjectName("inputStartTime")
        self.ptId_recInfo_fields.addWidget(self.inputStartTime, 16, 3, 1, 1)
        self.hospadmincodeedit = QtWidgets.QLineEdit(self.centralwidget)
        self.hospadmincodeedit.setEnabled(False)
        self.hospadmincodeedit.setObjectName("hospadmincodeedit")
        self.ptId_recInfo_fields.addWidget(self.hospadmincodeedit, 10, 3, 1, 1)
        self.techcode = QtWidgets.QLineEdit(self.centralwidget)
        self.techcode.setEnabled(False)
        self.techcode.setObjectName("techcode")
        self.ptId_recInfo_fields.addWidget(self.techcode, 11, 2, 1, 1)
        self.ptidotheredit = QtWidgets.QLineEdit(self.centralwidget)
        self.ptidotheredit.setEnabled(False)
        self.ptidotheredit.setObjectName("ptidotheredit")
        self.ptId_recInfo_fields.addWidget(self.ptidotheredit, 7, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.ptId_recInfo_fields.addWidget(self.label_8, 9, 1, 1, 1)
        self.equipcodeedit = QtWidgets.QLineEdit(self.centralwidget)
        self.equipcodeedit.setEnabled(False)
        self.equipcodeedit.setObjectName("equipcodeedit")
        self.ptId_recInfo_fields.addWidget(self.equipcodeedit, 12, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setObjectName("label_14")
        self.ptId_recInfo_fields.addWidget(self.label_14, 11, 1, 1, 1)
        self.hospcodeedit = QtWidgets.QLineEdit(self.centralwidget)
        self.hospcodeedit.setEnabled(False)
        self.hospcodeedit.setObjectName("hospcodeedit")
        self.ptId_recInfo_fields.addWidget(self.hospcodeedit, 3, 3, 1, 1)
        self.groupBoxDateEditrecInfo = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxDateEditrecInfo.setEnabled(False)
        self.groupBoxDateEditrecInfo.setTitle("")
        self.groupBoxDateEditrecInfo.setObjectName("groupBoxDateEditrecInfo")
        self.ptId_recInfo_fields.addWidget(self.groupBoxDateEditrecInfo, 9, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.ptId_recInfo_fields.addWidget(self.label_9, 4, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.ptId_recInfo_fields.addWidget(self.label_4, 9, 0, 1, 1)
        self.cbox_setdefaults = QtWidgets.QCheckBox(self.centralwidget)
        self.cbox_setdefaults.setEnabled(False)
        self.cbox_setdefaults.setChecked(True)
        self.cbox_setdefaults.setObjectName("cbox_setdefaults")
        self.ptId_recInfo_fields.addWidget(self.cbox_setdefaults, 2, 3, 1, 1)
        self.inputStartDate = QtWidgets.QDateEdit(self.centralwidget)
        self.inputStartDate.setEnabled(False)
        self.inputStartDate.setObjectName("inputStartDate")
        self.ptId_recInfo_fields.addWidget(self.inputStartDate, 15, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.ptId_recInfo_fields.addWidget(self.label_7, 3, 1, 1, 1)
        self.ptname = QtWidgets.QLineEdit(self.centralwidget)
        self.ptname.setEnabled(False)
        self.ptname.setObjectName("ptname")
        self.ptId_recInfo_fields.addWidget(self.ptname, 6, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setObjectName("label_13")
        self.ptId_recInfo_fields.addWidget(self.label_13, 10, 1, 1, 1)
        self.equipcode = QtWidgets.QLineEdit(self.centralwidget)
        self.equipcode.setEnabled(False)
        self.equipcode.setObjectName("equipcode")
        self.ptId_recInfo_fields.addWidget(self.equipcode, 12, 2, 1, 1)
        self.groupBoxDaterecInfo = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxDaterecInfo.setEnabled(False)
        self.groupBoxDaterecInfo.setTitle("")
        self.groupBoxDaterecInfo.setObjectName("groupBoxDaterecInfo")
        self.ptId_recInfo_fields.addWidget(self.groupBoxDaterecInfo, 9, 2, 1, 1)
        self.recinfootheredit = QtWidgets.QLineEdit(self.centralwidget)
        self.recinfootheredit.setEnabled(False)
        self.recinfootheredit.setObjectName("recinfootheredit")
        self.ptId_recInfo_fields.addWidget(self.recinfootheredit, 13, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setObjectName("label_10")
        self.ptId_recInfo_fields.addWidget(self.label_10, 5, 1, 1, 1)
        self.hospcode = QtWidgets.QLineEdit(self.centralwidget)
        self.hospcode.setEnabled(False)
        self.hospcode.setObjectName("hospcode")
        self.ptId_recInfo_fields.addWidget(self.hospcode, 3, 2, 1, 1)
        self.ptidother = QtWidgets.QLineEdit(self.centralwidget)
        self.ptidother.setEnabled(False)
        self.ptidother.setObjectName("ptidother")
        self.ptId_recInfo_fields.addWidget(self.ptidother, 7, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setObjectName("label_16")
        self.ptId_recInfo_fields.addWidget(self.label_16, 13, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setObjectName("label_18")
        self.ptId_recInfo_fields.addWidget(self.label_18, 15, 1, 1, 1)
        self.recinfoother = QtWidgets.QLineEdit(self.centralwidget)
        self.recinfoother.setEnabled(False)
        self.recinfoother.setObjectName("recinfoother")
        self.ptId_recInfo_fields.addWidget(self.recinfoother, 13, 2, 1, 1)
        self.groupBoxSex = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxSex.setEnabled(False)
        self.groupBoxSex.setTitle("")
        self.groupBoxSex.setObjectName("groupBoxSex")
        self.ptId_recInfo_fields.addWidget(self.groupBoxSex, 4, 2, 1, 1)
        self.layout.addLayout(self.ptId_recInfo_fields, 4, 0, 1, 2)
        self.lblInfo = QtWidgets.QLabel(self.centralwidget)
        self.lblInfo.setAutoFillBackground(False)
        self.lblInfo.setObjectName("lblInfo")
        self.layout.addWidget(self.lblInfo, 1, 0, 1, 2)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.layout.addWidget(self.line, 3, 0, 1, 2)
        self.lblFn = QtWidgets.QLabel(self.centralwidget)
        self.lblFn.setObjectName("lblFn")
        self.layout.addWidget(self.lblFn, 2, 0, 1, 2)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.layout)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 840, 22))
        self.menubar.setObjectName("menubar")
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setGeometry(QtCore.QRect(0, 0, 3, 27))
        self.statusbar.setObjectName("statusbar")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EDF Anonymizer"))
        self.btn_anonfile.setText(_translate("MainWindow", "Anonymize and save file"))
        self.label_6.setText(_translate("MainWindow", "Modified"))
        self.label_11.setText(_translate("MainWindow", "Patient name:"))
        self.cbox_copyoriginal.setText(_translate("MainWindow", "Copy original values"))
        self.oldinputStartDate.setDisplayFormat(_translate("MainWindow", "MM/dd/yyyy"))
        self.label_3.setText(_translate("MainWindow", "Patient ID:"))
        self.label_5.setText(_translate("MainWindow", "Original"))
        self.techcodeedit.setText(_translate("MainWindow", "X"))
        self.ptnameedit.setText(_translate("MainWindow", "X"))
        self.label_17.setText(_translate("MainWindow", "Start time:"))
        self.oldinputStartTime.setDisplayFormat(_translate("MainWindow", "hh:mm:ss"))
        self.label_12.setText(_translate("MainWindow", "Other:"))
        self.label_15.setText(_translate("MainWindow", "Equiptment code:"))
        self.inputStartTime.setDisplayFormat(_translate("MainWindow", "hh:mm:ss"))
        self.hospadmincodeedit.setText(_translate("MainWindow", "X"))
        self.label_8.setText(_translate("MainWindow", "Start date:"))
        self.equipcodeedit.setText(_translate("MainWindow", "X"))
        self.label_14.setText(_translate("MainWindow", "Technician code:"))
        self.hospcodeedit.setText(_translate("MainWindow", "X"))
        self.label_9.setText(_translate("MainWindow", "Sex:"))
        self.label_4.setText(_translate("MainWindow", "Recording information:"))
        self.cbox_setdefaults.setText(_translate("MainWindow", "Set default values"))
        self.inputStartDate.setDisplayFormat(_translate("MainWindow", "MM/dd/yyyy"))
        self.label_7.setText(_translate("MainWindow", "Hospital code:"))
        self.label_13.setText(_translate("MainWindow", "Hopsital admin code:"))
        self.label_10.setText(_translate("MainWindow", "Date of birth:"))
        self.label_16.setText(_translate("MainWindow", "Other:"))
        self.label_18.setText(_translate("MainWindow", "Start date:"))
        self.lblInfo.setText(_translate("MainWindow", "Select file to anonymize. Update fields and click anonymize and save to select location for new file."))
        self.lblFn.setText(_translate("MainWindow", "No file loaded. "))

