# This is a basic workflow to help you get started with Actions

name: Run tests

# Controls when the workflow will run
on:
  pull_request:
  push:
    branches:    
      # Push events on main branch
      # - main
      # Push events to branches matching refs/heads/mona/octocat
      - 'tests'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup python version
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install dependencies
        run: |
          pip install numpy==1.21.2  
          pip install -r requirements.txt
          
      - name: Run filter tests
        run: python tests/filter_test.py
        
      - name: Run tests
        run: |
         chmod +x ./run_tests.sh
         ./run_tests.sh
        shell: bash
        env:
          QT_QPA_PLATFORM: offscreen
